# Site settings
title: Jesse Brizzi
email: jbrizzi@cs.stonybrook.edu
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.jessebrizzi.com" # the base hostname & protocol for your site
repository: jessebrizzi/jessebrizzi.github.io


# ----------------------------------------------------------------------------
# Customize Options: Optional
#
# See: https://material.io/guidelines/style/color.html
# Use color-name-value, like pink-200 or deep-purple-100
brand_color: "gray"

# How article URLs are structured.
# See: https://jekyllrb.com/docs/permalinks/
permalink: :title/

# "UA-NNNNNNNN-N"
google_analytics: "UA-111786099-1"

# Language. For example, if you write in Japanese, use "ja"
lang: "en"

# How many posts are visible on the home page without clicking "View More"
num_posts_visible_initially: 10

# Date format: See http://strftime.net/
date_format: "%Y %b %-d"

google-drive-resume-file-id: 1qXzVxnPXS0bZL67kyx9YaPBJt7M6PR5v
# ----------------------------------------------------------------------------

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - mix-manifest.json
  - webpack.mix.js
  - yarn.lock
  - package.json
  - hot

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
